language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get update
  # https://electronjs.org/docs/tutorial/testing-on-headless-ci
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install electron-packager -g
install:
  - npm install
  - npm run packagerApp
notifications:
  slack:
      on_success: change
      on_failure: never
branches:
  only:
  - master
  - /^greenkeeper/.*$/
env:
  global :
      - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
